django-login/configg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('site/',include('inicialsite.urls')),
    path('', include('perfil.urls')),
    path('admin/', admin.site.urls),
]

django-login/inicialsite/urls.py
from django.urls import path
from .views import Dashboard, Busca

app_name='inicialsite'

urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard'),
    path('busca/', Busca.as_view(), name='busca'),
]

django-login/perfil/urls.py
from django.urls import path
from .views import Login,Logout,Cadastro,AtualizarPerfil, Deletarperfil
from django.urls import path, include
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView
from perfil.api.views import MyTokenObtainPairView
from perfil.api.viewsets import UserViewset
from rest_framework import routers


router = routers.DefaultRouter()
router.register(r'usuarios', UserViewset)

urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('cadastro/', Cadastro.as_view(), name='cadastro'),
    path('atualizarperfil/', AtualizarPerfil.as_view(), name='atualizar'),
    path('deletarperfil/', Deletarperfil.as_view(), name='deletarperfil'),

    #api django rest framework urls
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('api/', include(router.urls), name='api'),
    path('api/token/', MyTokenObtainPairView.as_view(), name='Token'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='refresh'),

]

django-login/templates/parciais/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">

django-login/templates/parciais/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

django-login/templates/parciais/_nav.html
{% load static %}


{% if request.user.is_authenticated %}
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'inicialsite:dashboard' %}">Meusite</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {%else%}
    <nav class="navbar navbar-dark bg-primary navbar-expand-lg">
        <a class="navbar-brand" href="{% url 'login' %}">Meusite</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% endif %}

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}

                <li class="nav-item dropdown">
                    <ul class="nav-item">
                        <li><a class="dropdown-item" href="{% url 'atualizar' %}">Meu perfil</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Sair</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cadastro' %}">Criar conta</a>
                </li>
                {% endif %}




            </ul>
            {% if request.user.is_authenticated%}
            <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'inicialsite:busca' %}">
                <input name="termo" value="{{ request.GET.termo }}" class="form-control mr-sm-2" type="search"
                    placeholder="Busca" aria-label="Busca">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Busca</button>
            </form>
            {%else%}



            {%endif%}

        </div>
    </nav>
</nav>

django-login/templates/parciais/_pagination.html
{% if is_paginated %}
<div class="pagination">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1">&laquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
        </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}

        {% if page_obj.number == num %}
        <li class="page-item active">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <li class="page-item">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
        {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endif %}